### ISSUE TITLE
CD 구축

### ISSUE THREAD

**Issue by seungh0** [mash-up-kr/muzily-backend-spring#14]
- [x] GitHub Actions 로 Docker Hub 에 이미지 푸시
- [x] 푸시 후 Helm Chart 업데이트
- [x] ArgoCD 싱크
- [x] wiki 배포하는 방법 작성

**Comment by y2o2u2n** [comment]
# 플로우

- `배포할 브랜치`, `버전`, `타겟 배포 환경`을 파라미터로 입력하고 배포 GitHub Action 을 실행
- 빌드된 이미지가 Docker Hub 에 등록됨
- 헬름 차트가 명시된 저장소에 `버전`이 업데이트됨
- ArgoCD 에서 자동 싱크하여 배포됨

## GitHub Actions

> yaml 업데이트는 이거 사용하면 될 듯... [@](https://github.com/fjogeleit/yaml-update-action)

- Jib 로 이미지 빌드 & Docker Hub 로 푸시
- 헬름 차트 내 yaml 업데이트

## ArgoCD

### 설치

> https://argo-cd.readthedocs.io/en/stable/getting_started/
> 위의 내용을 참고하여 편의상 Non HA 로 설치하여 사용한다.

- NodePort 에 적당한 포트를 사용

### 앱 설정

> https://www.youtube.com/watch?v=VyuVFtp2-2M
