### ISSUE TITLE
카카오 Auth APi Docs

### ISSUE THREAD

**Issue by seungh0** [mash-up-kr/muzily-backend-spring#22]
### 1. authorization_code

https://kauth.kakao.com/oauth/authorize?client_id={{CLIENT_ID}}&redirect_uri=http://localhost:3000/auth/kakao/callback&response_type=code

- {{CLIENT_ID}}: REST API Auth Key

호출시 Path로 넘어오는 code값 => authorization_code

ex) http://localhost:3000/auth/kakao/callback?code=Tba72k1SF5qtmqAk9fBTuQKMRiyOoc7UIYVFTxkihH_ym34k9l0i6ySz0S1k8Dt-0wsuFAopb1QAAAGBpSzuwg

```json
POST http://118.67.142.9/api/v1/auth

{
    "code": "{{CODE}}",
    "redirectUri":"http://localhost:3000/auth/kakao/callback", // 클라에 맞게 변경해주세요~
    "socialType": "KAKAO"
}
```

### Response (200 OK)
```json
{
    "code": "",
    "message": "",
    "data": {
        "token": "{{SESSION_ID}}" // 세션 ID -> {{SESSION_ID}}
    }
}
```

## 에러 코드
> 요거 임시로 잡은거여서.. 바뀔 예정입니다 (디버깅 목적으로만 일단... 사용 부탁해요!)

### Error (400) - Wrong code, redirectUri
```json
{
    "code": "AT001",
    "message": "잘못된 인증 토큰입니다",
    "data": null
}
```

### Error (500) - Interal Server Error 
``` json
{
    "code": ""C006",
    "message": "서버에서 에러가 발생하였습니다 ㅠㅠ",
    "data": null
}
```

### 세션ID 이용하는 방법 (인증 체크)
```json
GET {{api}}](http://118.67.142.9)/api/v1/accounts
Authorization: Bearer {{SESSION_ID}} 
```

**Comment by manudeli** [comment]
아주 이해하기 좋구만

혹시 내일 시도해보다가 모르는거 있으면 다시 물어볼게요~
