### ISSUE TITLE
웹소켓 연결 테스트

### ISSUE THREAD

**Issue by y2o2u2n** [mash-up-kr/muzily-backend-spring#25]
https://chrome.google.com/webstore/detail/apic-complete-api-solutio/ggnhohnkfcpcanfekomdkjffnfcjnjam

위 툴로 websocket stomp 테스트 진행 (방에다가 채팅하는...)

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/45726850/175976334-5ae0d2d1-3c89-4e58-8a17-03da51b3675c.png">

---

1. 방 생성
```
curl -d '{"description":"테스트 방"}' \
-H "Content-Type: application/json" \
-X POST http://118.67.142.9/api/v1/rooms

{"code":"","message":"","data":{"roomId":1,"description":"테스트 방","createdAt":[2022,6,28,0,15,41,714746000],"updatedAt":[2022,6,28,0,15,41,714746000]}}%              
```

2. Request URL 입력 : ws://118.67.142.9/ws
3. Connection Type 선택 : Stomp
4. Subscription URL 입력 :  /sub/v1/rooms/1
5. Connect 버튼 클릭
6. Destination Queue 입력 : /pub/v1/rooms/1/chats
7. Send 버튼 클릭
8. Messages 확인

---

StompJS 로 연결해보면 될 듯...!
기능 개발하게 되면 응답 포맷이라던가 구체화를 할게
그리고 웹소켓이 적절한 문서화 도구가 없는 것 같은데
혹시 아는거 있는 사람 있으면 알려줘...!

**Comment by y2o2u2n** [comment]
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/45726850/175977602-468e8db2-ee4c-4131-b9b8-54d2c75ae4d3.png">

이거는 에러 발생할 때 개인이 메세지 받기 위한 구독 경로

---

1. Request URL 입력 : ws://118.67.142.9/ws
2. Connection Type 선택 : Stomp
3. Subscription URL 입력 : /user/queue/errors
4. Connect 버튼 클릭
5. Destination Queue 입력 : /pub/v1/rooms/22/chats (없는 방에다가)
6. Send 버튼 클릭
7. Messages 확인

**Comment by manudeli** [comment]
오 요런 툴도 있구만~~ 꿀팁 줍줍
